name: Docker

on:
  push:
    branches:
      - main
jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
      password: ${{ secrets.GITHUB_TOKEN:}}

    - name: Build and push
      uses: docker/buil-push-action@v5
      with:
        push: true
        tags: ghcr.io/CharlelieL/ipme-charlelie:latest

